package vn.com.itechcorp.hsm.dto;

public enum SingletonSigningKey {
    PAGENO,
    POSITIONIDENTIFIER,
    RECTANGLEOFFSET,
    RECTANGLESIZE,
    VISIBLESIGNATURE,
    SHOWSIGNERINFO,
    SIGNERINFOPREFIX,
    SHOWDATETIME,
    DATETIMEPREFIX,
    SHOWREASON,
    SIGNREASONPREFIX,
    SIGNREASON,
    DATETIMEFORMAT,
    SHOWLOCATION,
    LOCATION,
    LOCATIONPREFIX
}
